[[redirects]]
  from = "/capstone"
  to = "https://www.youtube.com/watch?v=cSDPUYppi0Q"
[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/1Lt8GbqB7RgW7C5B68toSvlm8_NoPICYQ/view?usp=sharing"


