[[redirects]]
  from = "/capstone"
  to = "https://www.youtube.com/watch?v=cSDPUYppi0Q"
[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/1BJ19GIJTn1u-yOItup6T0Y_WdrecieSN/view?usp=sharing"


